version: "3"
services:
  app-node:
    build:
      context: ./app-node # Thư mục chứa Dockerfile cho Node.js
    ports:
      - "3000:3000" # Cổng container Node.js sẽ chạy trên cổng 3000
    mem_limit: 1g # Giới hạn bộ nhớ 1GB
    cpus: 1.0
    volumes:
      - ./app-node:/usr/src/app # Mount thư mục app-node vào container
      - /usr/src/app/node_modules
    networks:
      - app-network

  app-golang:
    build:
      context: ./app-golang # Thư mục chứa Dockerfile cho Go
    ports:
      - "8888:8888" # Cổng container Go sẽ chạy trên cổng 8080
    mem_limit: 1g # Giới hạn bộ nhớ 1GB
    cpus: 1.0
    volumes:
      - ./app-golang:/usr/src/app # Mount thư mục app-golang vào container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
